services:
  backend:
    container_name: bilinote-backend
    build:
      context: .
      dockerfile: backend/Dockerfile.china 
      x-bake:
        platforms:
          - linux/arm64
    env_file:
      - .env
    dns:
      - 223.5.5.5 
      - 119.29.29.29  
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - BACKEND_HOST=${BACKEND_HOST}
      - HOST_GATEWAY=${HOST_GATEWAY:-172.18.0.1}  # 可配置的网关IP
    # volumes:
    #   - ./backend:/app
    expose:
      - '${BACKEND_PORT}'
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Docker内置的宿主机访问方式
      - "api.host:host-gateway"  # 给网关一个友好的名称
    networks:
      - default
      - new-api_default  # 连接到new-api网络

  frontend:
    container_name: bilinote-frontend
    build:
      context: .
      dockerfile: BillNote_frontend/Dockerfile.china
      x-bake:
        platforms:
          - linux/arm64
    expose:
      - '80'

  nginx:
    container_name: bilinote-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - '${APP_PORT}:80'
    depends_on:
      - backend
      - frontend

networks:
  default:
    name: bilinote_default
  new-api_default:
    external: true  # 使用已存在的new-api网络
