services:
  backend:
    container_name: bilinote-backend
    build:
      context: .
      dockerfile: backend/Dockerfile.china 
      args:
        - HTTP_PROXY=http://host.docker.internal:7890
        - HTTPS_PROXY=http://host.docker.internal:7890
      x-bake:
        platforms:
          - linux/arm64
    env_file:
      - .env
    dns:
      - 223.5.5.5 
      - 119.29.29.29  
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - BACKEND_HOST=${BACKEND_HOST}
    # volumes:
    #   - ./backend:/app
    expose:
      - '${BACKEND_PORT}'

  frontend:
    container_name: bilinote-frontend
    build:
      context: .
      dockerfile: BillNote_frontend/Dockerfile.china
      x-bake:
        platforms:
          - linux/arm64
    expose:
      - '80'

  nginx:
    container_name: bilinote-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - '${APP_PORT}:80'
    depends_on:
      - backend
      - frontend
