
services:
  backend:
    container_name: bilinote-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - BACKEND_HOST=${BACKEND_HOST}
      - HOST_GATEWAY=${HOST_GATEWAY:-172.18.0.1}  # 可配置的网关IP
    expose:
      - "${BACKEND_PORT}"  # 不再对外暴露，用于 nginx 内部通信
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Docker内置的宿主机访问方式
      - "api.host:host-gateway"  # 给网关一个友好的名称
    networks:
      - default
      - new-api_default  # 连接到new-api网络

  frontend:
    container_name: bilinote-frontend
    build:
      context: .
      dockerfile: BillNote_frontend/Dockerfile
    env_file:
      - .env
    expose:
      - "80"  # 不暴露给宿主机，只供 nginx 访问

  nginx:
    container_name: bilinote-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - backend
      - frontend

networks:
  default:
    name: bilinote_default
  new-api_default:
    external: true  # 使用已存在的new-api网络
